name: SD3HF
channels:
  - pytorch
  - nvidia
  - conda-forge
  #LINUX ONLY
  #- xformers
dependencies:
  - python=3.12.4
  - pip
  - pytorch::pytorch=2.3.1
  - pytorch::torchvision 
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - conda-forge::huggingface_hub
  - conda-forge::transformers
  - conda-forge::diffusers
  - conda-forge::accelerate
  - conda-forge::sentencepiece
  - conda-forge::protobuf
  - conda-forge::matplotlib
  #LINUX ONLY
  #- xformers::xformers
  - nbconvert
  - ipykernel
  - jupyterlab
  
  #WINDOWS ONLY
  #- pip:
    #- xformers
  #Actually you have to install this manaually to stop it overriding the current version
  # of torch (and therefore destorying the cuda acceleration). Note that conda doesn't
  # seem to be able to use flags for pip installs from an environment.yml file.
  # pip install -U xformers --index-url https://download.pytorch.org/whl/cu121
